language: node_js
node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - sonar-scanner
  - yarn build

dist: trusty

addons:
  sonarcloud:
    organization: "rawfg-github"
    token:
      secure: $SONAR_TOKEN

deploy:
  provider: surge
  skip_cleanup: true
  domain: chwaeth.surge.sh
  project: ./build/

on:
  master